services:
  - type: web
    name: bigbreakingwire-video-studio
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: CHROME_BIN
        value: /usr/bin/chromium
